### ISSUE TITLE
How to test NBIoT usecase with this test setup

### ISSUE THREAD

**Issue by sajujohnsebastian** [fasferraz/eNB#12]
Hello Team,
I am trying to explore various 4G/5G test setups and came across this useful link. I was able to set this and were able to test Open5Gs setup using eNB Emulator. I see that there is support for NBIoT as well and would like to validate that as well.
Could you share some insights on how can NBIoT be tested.

Thanks&Regards,
Saju

**Comment by fasferraz** [comment]
Hi Saju,
you need to do this before activating s1 (option 15) oand doing attach (option 20):
1. You need to set s1 setup type to NBIot or both - This is done using option 1
Nbiot uses another TAC. you can change it in code ENB-TAC-NBIOT (by default is tac 2):
```
session_dict['ENB-TAC-NBIOT'] = b'\x00\x02'  
```
2. Then you need to change session type to NB-Iot using option 4.
3. For PSM and/or eDRX you use option 5.
I used some fixed values in code for PSM and eDRX, but you can change them to meet your needs (this next code is in eNB_LOCAL.py file, line 866):

```
        if type[1] == "PSM" or type[1] == "BOTH":
            emm_list.append((0x6A, 'TLV', b'\x0f')) # 15*2=30 sec.
            emm_list.append((0x5E, 'TLV', b'\x41'))
        if type[1] == "EDRX" or type[1] == "BOTH":
            emm_list.append((0x6E, 'TLV', b'\x75'))
```

**Comment by sajujohnsebastian** [comment]
Thanks @fasferraz . 
I see that we can make these configuration changes to eNB to make it support NBIoT. But on the other side, open5Gs should also be able to support NBIoT for establishing end to end communication. From what I have understood Open5GS has not started to support NBIoT (https://open5gs.org/open5gs/features/). 
So were you able to test NBIoT ?

**Comment by fasferraz** [comment]
I had an MME from a well known vendor that supported NB-Iot feature (in my previous job).
So I was able to test my eNB in lab with that MME.

**Comment by sajujohnsebastian** [comment]
Thanks for the info @fasferraz . I think I will wait for NB-IoT
