### ISSUE TITLE
User plane not working (GTP-U)

### ISSUE THREAD

**Issue by dchard** [fasferraz/eNB#6]
Dear @fasferraz 

Everything works great up until the point I try to send some IP data across the GTP-U tunnel (towards the SGW).

S1 setup succeeds
Attach succeeds

```
2022-12-27 18:56:03.207215: S1AP: sending S1SetupRequest                                                    |
2022-12-27 18:56:03.217254: S1AP: S1SetupResponse received                                                  |
2022-12-27 18:56:04.751138: S1AP: sending InitialUEMessage                                                  |
2022-12-27 18:56:04.857392: S1AP: DownlinkNASTransport received                                             |
2022-12-27 18:56:04.860707: NAS: AuthenticatonRequest received                                              |
2022-12-27 18:56:04.865603: S1AP: sending UplinkNASTransport                                                |
2022-12-27 18:56:04.875660: S1AP: DownlinkNASTransport received                                             |
2022-12-27 18:56:04.878713: NAS: SecurityMode received                                                      |
2022-12-27 18:56:04.928814: NAS: sending SecurityModeComplete                                               |
2022-12-27 18:56:04.931396: S1AP: sending UplinkNASTransport                                                |
2022-12-27 18:56:05.039040: S1AP: InitialContextSetupRequest received                                       |
2022-12-27 18:56:05.041977: S1AP: sending InitialContextSetupResponse                                       |
2022-12-27 18:56:05.044763: NAS: AttachAccept received                                                      |
2022-12-27 18:56:05.047482: [('apn', 'dyn.delta')]                                                          |
2022-12-27 18:56:05.050234: [('pdn type value', 1), ('ipv4', '10.45.0.4')]                                  |
2022-12-27 18:56:05.057832: [('type of identity', 6), ('mcc', 101), ('mnc', 10), ('mme group id', 100), ('m |
2022-12-27 18:56:05.057832: me code', 101), ('m-tmsi', 69), ('s-tmsi', b'e\x00\x00\x00E')]                  |
2022-12-27 18:56:05.060878: NAS: sending AttachComplete                                                     |
2022-12-27 18:56:05.101081: S1AP: sending UplinkNASTransport     
```

After this, a tun1 named interface is already present with IP 10.45.0.4 set.

I add the proper route back: `ip route add 10.45.0.0/24 dev tun1`

When I try to ping 10.45.0.1 (the SGW side) no response is coming back, tshark records ICMP requests outside of the tunnel:

```
Capturing on 'tun1'
    1 0.000000000    10.45.0.4 → 10.45.0.1    ICMP 84 Echo (ping) request  id=0x0004, seq=122/31232, ttl=64
    2 1.023971084    10.45.0.4 → 10.45.0.1    ICMP 84 Echo (ping) request  id=0x0004, seq=123/31488, ttl=64
    3 2.047980988    10.45.0.4 → 10.45.0.1    ICMP 84 Echo (ping) request  id=0x0004, seq=124/31744, ttl=64
    4 3.071968997    10.45.0.4 → 10.45.0.1    ICMP 84 Echo (ping) request  id=0x0004, seq=125/32000, ttl=64
    5 4.095967761    10.45.0.4 → 10.45.0.1    ICMP 84 Echo (ping) request  id=0x0004, seq=126/32256, ttl=64
```

When I try to ping 10.45.0.4 from the SGW, the GTP-U encapsulated packets are arriving correctly, but no response:

```
Capturing on 'ens18'
    1 0.000000000 10.253.250.51 → 10.253.250.221 GTP 54 Echo request
    2 0.000388885 10.253.250.221 → 10.253.250.51 GTP 56 Echo response
    3 0.577967074    10.45.0.1 → 10.45.0.4    GTP <ICMP> 134 Echo (ping) request  id=0x1a28, seq=1/256, ttl=64
    4 1.579006583    10.45.0.1 → 10.45.0.4    GTP <ICMP> 134 Echo (ping) request  id=0x1a28, seq=2/512, ttl=64
    5 2.579048708    10.45.0.1 → 10.45.0.4    GTP <ICMP> 134 Echo (ping) request  id=0x1a28, seq=3/768, ttl=64
    6 3.580070569    10.45.0.1 → 10.45.0.4    GTP <ICMP> 134 Echo (ping) request  id=0x1a28, seq=4/1024, ttl=64
    7 4.580065463    10.45.0.1 → 10.45.0.4    GTP <ICMP> 134 Echo (ping) request  id=0x1a28, seq=5/1280, ttl=64
```

Seemingly every works a it should, the routes are correct, IPs are correct, yet the userplane part is not passing.

Firewall is disabled on both sides, IP_forwarding is enabled on both sides.

**Comment by fasferraz** [comment]
Hi, you don't need to configure any route, the app does it for you. What you need to do after the establishment of the session is to activate option 50 to allow User Plane. Option 51 deactivates it.

**Comment by dchard** [comment]
> Hi, you don't need to configure any route, the app does it for you. What you need to do after the establishment of the session is to activate option 50 to allow User Plane. Option 51 deactivates it.

Ahh, I thought after S1 setup and Attach, when the TUN interface is up and available it can already forward data. :-)

In the mean time I already tried the GTP Dialer, and it works great (I need to test GTP-U performance). The only problem is the performance. Around 300Mbit the single core load start to get really high and the net stack starts to loose packets. One way you can improve the performance is to use the kernel GTP stack. It is rather easy to integrate it and it is supported since kernel 4.7.0. Most mainline linux distros already shipped with a kernel which has GTP enabled. Both the GTP Dialer and the eNB emulator could benefit greatly from this.

Another thing is this default route creation. In most test environments this is rather annoying (I already removed that part of the code), maybe a flag to disable this behavior would improve the user experience :-)

**Comment by fasferraz** [comment]
Thanks for your suggestions! 
Regarding default route, the best thing is to use namespace option in gtp_dialer (-N), this way the default route and tunnel are created inside a namespace. I didn't have the time to add that option also to eNB.
Gtp dialer has a predefined APN-AMBR set to 300Mbits (0x493e0):

def add_ambr_v2():
    return b'\x48\x00\x08\x00\x00\x04\x93\xe0\x00\x04\x93\xe0' 

I find strange that the value you see as limit is this one.
Can you change it to 1Gbps and try again?

def add_ambr_v2():
    return b'\x48\x00\x08\x00\x00\x0f\x42\x40\x00\x0f\x42\x40'

**Comment by dchard** [comment]
> def add_ambr_v2():
> return b'\x48\x00\x08\x00\x00\x0f\x42\x40\x00\x0f\x42\x40'

Yep, already found and edited that part :-)

The below test is with the 1gbit AMBR set, and 400Mbits of UDP traffic sent towards the GTP-Dialer:

![image](https://user-images.githubusercontent.com/8152156/209743568-16b2a442-6aa2-44b5-9278-85848e5da551.png)

This means that the realistic end of this is around 5-600Mbits in a virtualized environment, and not scaling due to the single thread limit.

Utilizing the kernel GTP driver can substantially speed this up. 

To work with the GTP kernel driver, you need to:

- `modporbe gtp` (or gtp.ko)
- and you need libgtpnl: https://cgit.osmocom.org/libgtpnl/
  libgtpnl also contains the user space tools of `gtp-link` and `gtp-device` which can be used to create and manage GTP devices and links.

**Comment by dchard** [comment]
@fasferraz FYI, I continued testing the performance and it seems I was right: the stack can take about 500Mbit traffic, then it starts to loose packets. At 600Mbits there is more than 10% loss and I hit single core limit (100% CPU, most of it is system as expected). And this was just a single direction test.

**Comment by fasferraz** [comment]
Hi, updated gtp_dialer to support gtp kernel driver/libgtpnl
Can you try? You need to add option -Z
I was not able to do it inside namespace, for now you have to do it outside.

**Comment by dchard** [comment]
> Can you try?

I am happy to. 👍 

Let me do my test and get back to you.

**Comment by dchard** [comment]
@fasferraz I continued to test this today, and I managed to break one opensource and one small enterprise core's GTP stack with it. Both of them broke pretty close to each other: at around 650Mbits. In the same time, your tool is doing just fine, no loss on the interface, nor the IP nor the UDP sockets. So we don't know how fast it can get, because the DUT breaks way before we can reach that limit :-) Which is really great.

**Comment by fasferraz** [comment]
ahaha amazing :) I never created these tools with speed on my mind, it was mostly for signaling and simple user plane tests (browsing, applications) for DPI/differentiated charging, but knowing that it can go to those speeds is really cool! :) 
Thanks for your suggestions!
I will try to add this functionality to namespace, but i think i need to create a bridge interface between namespace and host, and use a different IP for GTP-U, or alternatively I need to create a interface between them and do NAT or something... But is not so straightforward as using default namespace.
Have a nice 2023!

**Comment by dchard** [comment]
@fasferraz in terms of routing, the single most annoying thing is that GTP-Dialer try to add default route, while most of the case these tools run in a testbed, where the last thing you want is a tool modifying routes (especially default routes) based on bearer activation. Which drops every connection including SSH and other monitoring tools. I managed to comment out that part of the code.

A better method would be for the user to configure what route(s) needed on bearer/session creation to be added to the GTP interface. But definitely not a default route :-)

A minor bug I noticed is that when I first run the GTP_Dialer, the first 3-4 runs I got a `4. Answer received but decode failed. Deleting route to SGW/PGW created in step 1. Exiting` error. After 3-4 tries the session comes up:

```
1. Adding route to GGSN IP Address pointing to the current default gateway
 2. Creating GTP-C Socket
 3. Sending Create Session Request to SGW/PGW
 4. Answer received and GTPv2 decoded.
    => PGW GTP-U IP Adresss: 10.253.250.51
    => PGW GTP-C IP Adresss: 10.253.250.51
    => End-User IPv4 Adresss: 10.45.0.3
    => TEID Data Remote: 2440582454
    => TEID Control Remote: 1302651610
    => DNS Addresses Ipv4: None
    => DNS Addresses IPv6: None
 8. Configuring End User Address in the Tunnel interface
cmd: ip addr add 10.45.0.3/32 dev lo
cmd: gtp-link add gtp1 --sgsn > /tmp/log-gtp-link1 2>&1 &
cmd: gtp-tunnel add gtp1 v1 192296548 2440582454 10.45.0.3 10.253.250.51
```

This Wireshark capture has 3 failed attempts, and a 4th one which succeeds:

[gtp_dialer_answer_received_but_decode_failed.zip](https://github.com/fasferraz/eNB/files/10326052/gtp_dialer_answer_received_but_decode_failed.zip)

**Comment by fasferraz** [comment]
the app tries to emulate a dialer/dongle, and that is what usually happens: you activate a session in a dongle, and automatically that connection becomes the default route for everything. For more advanced users, that could be annoying. I can try to add a new option
Regarding the trace, your analysis is correct. when app starts and a CreateSessionRequest/CreatePDPContextRequest is sent what is expected is an answer to those messages. I will try to solve that issue.

**Comment by fasferraz** [comment]
I updated the app to solve your bug. I also added option -X to not install default route. can you test it please?

**Comment by dchard** [comment]
@fasferraz thanks, everything works now as it should. Both the -X and the protocol fix.

I wish you all the best for 2023! Will continue using the GTP_Dialer, will report back if I find anything. If you can port these to the eNB_emulator (especially the kernel GTP_driver) that would be awesome.

**Comment by dchard** [comment]
@fasferraz I wonder if you can port these changes (kernel GTP_U and "no default route") to the eNB app by any chance? Would be really nice and useful. I am using them with the gtp_dialer so far and they are great, did not find any bugs, performance is also very nice. But for some tests the only way is to use it is to integrate it to the eNB app.

**Comment by fasferraz** [comment]
I will try to do it. Just need to find some free time.

**Comment by fasferraz** [comment]
I added option -Z for kernel GTP_U. Please test. the "no default route" is already implemented since option 50/51 is used to activate/deactivate default route.
